add_filter('woocommerce_states', 'saudi_cities');

function saudi_cities($states) {
    $states['SA'] = array(
        'sa-01' => _x('الرياض', 'woocommerce'),
            'sub-sa-01' => _x('الدرعية', 'woocommerce'),
            'sub-sa-02' => _x('الخرج', 'woocommerce'),
            'sub-sa-03' => _x('الدوادمي', 'woocommerce'),
            'sub-sa-04' => _x('المجمعة', 'woocommerce'),
            'sub-sa-05' => _x('القويعية', 'woocommerce'),
            'sub-sa-06' => _x('الأفلاج', 'woocommerce'),
            'sub-sa-07' => _x('وادي الدواسر', 'woocommerce'),
            'sub-sa-08' => _x('الزلفي', 'woocommerce'),
            'sub-sa-09' => _x('شقراء', 'woocommerce'),
            'sub-sa-10' => _x('حوطة بني تميم', 'woocommerce' ),
            'sub-sa-11' => _x('عفيف', 'woocommerce' ),
            'sub-sa-12' => _x('الغاط', 'woocommerce' ),
            'sub-sa-13' => _x('السليل', 'woocommerce' ),
            'sub-sa-14' => _x('ضرماء', 'woocommerce' ),
            'sub-sa-15' => _x('المزاحمية', 'woocommerce' ),
            'sub-sa-16' => _x('رماح', 'woocommerce' ),
            'sub-sa-17' => _x('ثادق', 'woocommerce' ),
            'sub-sa-18' => _x('حريملاء', 'woocommerce' ),
            'sub-sa-19' => _x('الحريق', 'woocommerce' ),
            'sub-sa-20' => _x('مرات', 'woocommerce' ),
            'sub-sa-21' => _x('الدلم', 'woocommerce' ),
            'sub-sa-22' => _x('الرين', 'woocommerce' ),
        
        'sa-02' => _x('مكة المكرمة', 'woocommerce'),
            'sub-sa-23' => _x('جدة', 'woocommerce'),
            'sub-sa-24' => _x('الطائف', 'woocommerce'),
            'sub-sa-25' => _x('القنفذة', 'woocommerce'),
            'sub-sa-26' => _x('الليث', 'woocommerce'),
            'sub-sa-27' => _x('رابغ', 'woocommerce'),
            'sub-sa-28' => _x('خليص', 'woocommerce'),
            'sub-sa-29' => _x('الخرمة', 'woocommerce'),
            'sub-sa-30' => _x('رنية', 'woocommerce'),
            'sub-sa-31' => _x('تربة', 'woocommerce'),
            'sub-sa-32' => _x('الجموم', 'woocommerce'),
            'sub-sa-33' => _x('الكامل', 'woocommerce'),
            'sub-sa-34' => _x('المويه', 'woocommerce'),
            'sub-sa-35' => _x('ميسان', 'woocommerce'),
            'sub-sa-36' => _x('أضم', 'woocommerce'),
            'sub-sa-37' => _x('العرضيات', 'woocommerce'),
            'sub-sa-38' => _x('بحرة', 'woocommerce'),
        
        'sa-03' => _x('المدينة المنورة', 'woocommerce'),
            'sub-sa-39' => _x('ينبع', 'woocommerce'),
            'sub-sa-40' => _x('العلا', 'woocommerce'),
            'sub-sa-41' => _x('المهد', 'woocommerce'),
            'sub-sa-42' => _x('الحناكية', 'woocommerce'),
            'sub-sa-43' => _x('بدر', 'woocommerce'),
            'sub-sa-44' => _x('خيبر', 'woocommerce'),
            'sub-sa-45' => _x('العيص', 'woocommerce'),
            'sub-sa-46' => _x('وادي الفرع', 'woocommerce'),
        
        'sa-04' => _x('المنطقة الشرقية', 'woocommerce'),
            'sub-sa-47' => _x('الأحساء', 'woocommerce'),
            'sub-sa-48' => _x('حفر الباطن', 'woocommerce'),
            'sub-sa-49' => _x('الجبيل', 'woocommerce'),
            'sub-sa-50' => _x('القطيف', 'woocommerce'),
            'sub-sa-51' => _x('الخبر', 'woocommerce'),
            'sub-sa-52' => _x('العديد', 'woocommerce'),
            'sub-sa-53' => _x('الخفجي', 'woocommerce'),
            'sub-sa-54' => _x('رأس تنورة', 'woocommerce'),
            'sub-sa-55' => _x('ابقيق', 'woocommerce'),
            'sub-sa-56' => _x('النعيرية', 'woocommerce'),
            'sub-sa-57' => _x('قرية العليا', 'woocommerce'),
            'sub-sa-58' => _x('البيضاء', 'woocommerce'),
        
        'sa-05' => _x('القصيم', 'woocommerce'),
            'sub-sa-59' => _x('عنيزة', 'woocommerce'),
            'sub-sa-60' => _x('الرس', 'woocommerce'),
            'sub-sa-61' => _x('المذنب', 'woocommerce'),
            'sub-sa-62' => _x('البكيرية', 'woocommerce'),
            'sub-sa-63' => _x('البدائع', 'woocommerce'),
            'sub-sa-64' => _x('الأسياح', 'woocommerce'),
            'sub-sa-65' => _x('النبهانية', 'woocommerce'),
            'sub-sa-66' => _x('الشماسية', 'woocommerce'),
            'sub-sa-67' => _x('عيون الجواء', 'woocommerce'),
            'sub-sa-68' => _x('رياض الخبراء', 'woocommerce'),
            'sub-sa-69' => _x('عقلة الصقور', 'woocommerce'),
            'sub-sa-70' => _x('ضريه', 'woocommerce'),
        
        'sa-06' => _x('حائل', 'woocommerce'),
            'sub-sa-71' => _x('بقعاء', 'woocommerce'),
            'sub-sa-72' => _x('الغزالة', 'woocommerce'),
            'sub-sa-73' => _x('الشنان', 'woocommerce'),
            'sub-sa-74' => _x('الحائط', 'woocommerce'),
            'sub-sa-75' => _x('السليمي', 'woocommerce'),
            'sub-sa-76' => _x('الشملي', 'woocommerce'),
            'sub-sa-77' => _x('موقق', 'woocommerce'),
            'sub-sa-78' => _x('سميراء', 'woocommerce'),
        
        'sa-07' => _x('تبوك', 'woocommerce'),
            'sub-sa-79' => _x('الوجه', 'woocommerce'),
            'sub-sa-80' => _x('ضباء', 'woocommerce'),
            'sub-sa-81' => _x('تيماء', 'woocommerce'),
            'sub-sa-82' => _x('أملج', 'woocommerce'),
            'sub-sa-83' => _x('حقل', 'woocommerce'),
            'sub-sa-84' => _x('البدع', 'woocommerce'),
        
        'sa-08' => _x('الحدود الشمالية', 'woocommerce'),
            'sub-sa-85' => _x('رفحاء', 'woocommerce'),
            'sub-sa-86' => _x('طريف', 'woocommerce'),
            'sub-sa-87' => _x('العويقلية', 'woocommerce'),
        
        'sa-09' => _x('جازان', 'woocommerce'),
            'sub-sa-88' => _x('صبياء', 'woocommerce'),
            'sub-sa-89' => _x('أبو عريش', 'woocommerce'),
            'sub-sa-90' => _x('صامطة', 'woocommerce'),
            'sub-sa-91' => _x('الدرب', 'woocommerce'),
            'sub-sa-92' => _x('بيش', 'woocommerce'),
            'sub-sa-93' => _x('الحرث', 'woocommerce'),
            'sub-sa-94' => _x('ضمد', 'woocommerce'),
            'sub-sa-95' => _x('الريث', 'woocommerce'),
            'sub-sa-96' => _x('جزر فرسان', 'woocommerce'),
            'sub-sa-97' => _x('الدائر', 'woocommerce'),
            'sub-sa-98' => _x('أحد المسارحة', 'woocommerce'),
            'sub-sa-99' => _x('العيدابي', 'woocommerce'),
            'sub-sa-100' => _x('العارضة', 'woocommerce'),
            'sub-sa-101' => _x('فيفا', 'woocommerce'),
            'sub-sa-102' => _x('الطوال', 'woocommerce'),
            'sub-sa-103' => _x('هروب', 'woocommerce'),
        
        'sa-10' => _x('نجران', 'woocommerce'),
            'sub-sa-104' => _x('شرورة', 'woocommerce'),
            'sub-sa-105' => _x('حبونا', 'woocommerce'),
            'sub-sa-106' => _x('بدر الجنوب', 'woocommerce'),
            'sub-sa-107' => _x('يدمة', 'woocommerce'),
            'sub-sa-108' => _x('ثار', 'woocommerce'),
            'sub-sa-109' => _x('خباش', 'woocommerce'),
        
        'sa-11' => _x('منطقة الباحة', 'woocommerce'),
            'sub-sa-110' => _x('بلجرشي', 'woocommerce'),
            'sub-sa-111' => _x('المندق', 'woocommerce'),
            'sub-sa-112' => _x('المخواة', 'woocommerce'),
            'sub-sa-113' => _x('قلوة', 'woocommerce'),
            'sub-sa-114' => _x('العقيق', 'woocommerce'),
            'sub-sa-115' => _x('القرى', 'woocommerce'),
            'sub-sa-116' => _x('بني حسن', 'woocommerce'),
            'sub-sa-117' => _x('غامد الزناد', 'woocommerce'),
            'sub-sa-118' => _x('الحجرة', 'woocommerce'),
        
        'sa-12' => _x('الجوف', 'woocommerce'),
            'sub-sa-119' => _x('القريات', 'woocommerce'),
            'sub-sa-120' => _x('دومة الجندل', 'woocommerce'),
            'sub-sa-121' => _x('طبرجل', 'woocommerce'),

        'sa-13' => _x('عسير', 'woocommerce'),
            'sub-sa-122' => _x('خميس مشيط', 'woocommerce'),
            'sub-sa-123' => _x('بيشة', 'woocommerce'),
            'sub-sa-124' => _x('النماص', 'woocommerce'),
            'sub-sa-125' => _x('محايل', 'woocommerce'),
            'sub-sa-126' => _x('ظهران الجنوب', 'woocommerce'),
            'sub-sa-127' => _x('تثليث', 'woocommerce'),
            'sub-sa-128' => _x('سراة عبيدة', 'woocommerce'),
            'sub-sa-129' => _x('رجال ألمع', 'woocommerce'),
            'sub-sa-130' => _x('بلقرن', 'woocommerce'),
            'sub-sa-131' => _x('أحد رفيدة', 'woocommerce'),
            'sub-sa-132' => _x('المجاردة', 'woocommerce'),
            'sub-sa-133' => _x('البرك', 'woocommerce'),
            'sub-sa-134' => _x('بارق', 'woocommerce'),
            'sub-sa-135' => _x('تنومة', 'woocommerce'),
            'sub-sa-136' => _x('الحرجه', 'woocommerce'),
            'sub-sa-137' => _x('طريب', 'woocommerce'),
            'sub-sa-138' => _x('الامواه', 'woocommerce'),
    );

    return $states;
}
